pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["coprogramumi.htm","What program can","What program can Previous Top Next The program allows you to: -editing the phone book of any handset of the base according to the user&#39;s selection...",""],
["introduction.htm","Introduction ","Introduction Next Why was the program created What program can The technology used ",""],
["otestovanakonfigurace.htm","Tested configuration ","Tested configuration Previous Top Next -the program tested with base Gigaset C610 IP and the handsets Gigaset 610H, 620 h -in theory it should be ...",""],
["pouite_technologie.htm","The technology used","The technology used Previous Top Next The Program was created in the programming language Object Pascal with help of development environment CodeT...",""],
["požadavky_programu.htm","Program requirements","Program requirements Previous Top Next VoIP hardware Tested configuration System requirements ",""],
["pro_tento_program_vznikl.htm","Why was the program created","Why was the program created Previous Top Next This program was created due to simple reason. After we had purchased the home VOIP phone GIGASET 61...",""],
["systemove.htm","System requirements","System requirements The previous Top -at least 32 bit win7. -functional Internet connection ",""],
["voiphardware.htm","VoIP hardware ","VoIP hardware Previous Top Next -correctly configured telephone base Gigaset 610IP in LAN -theoretically compatible with all Gigaset IP bases, whi...",""]];
